# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:OC8DAQ8Y50Mr01M0Vl+LwHbUtw==,iv:ziQSQBNU1hlvGw6BaM21mY7UWr1xH9cEiA/IS+rN4QY=,tag:6ZePt81tmu42h8SoeHMUCQ==,type:str]
    api-key: ENC[AES256_GCM,data:S1qhaQx9i7u+pAvLObHMZZiaq1M=,iv:UPUaatrb6I22TIa+HNwoRcX+eFQ+bF0JbBRZJJAfDs4=,tag:Ou0wwm9H4fkk2ggSGpWesg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ut0l977a2jtal8kgswvu00zjzyh5k9cnudq0msswd9zyvm4jt34qe5n92g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVE9adkdlMlEwZURKY0pT
            bE1jZWd3WHcxUUMwcXEyWE80ZndDa0JWdkZnCkZ0OWIxckdjNERhYWszMkc2RDlG
            T2NGY3U2T3FFRGZicDhYMXFnTk5NUjgKLS0tIEV4OStxeTFWa3RjTTgxK0hhUE1t
            Z1FJWGNiVVlQQ2VNYU9sejFZeXdlZXMKBfSjeAIDCnI5gDYP62D3F47WM//OEL8b
            ToSybOHX2VaO7Gas8sWFbbE55ngj5au1bCWXo7/FSk93IUzKvM2bew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-04T11:25:16Z"
    mac: ENC[AES256_GCM,data:Ghcm0BGboDHPk69z/rM5kssmxrynbV5yNkyJC1KXplmVKHJaljVjuBYvE4Q7uASualf1/sSgUSf3hasi/7NYcMgDbApjismmn2Rt1r058HPnLqhVDo4LKa2CxaCmjtj3T+f+A4VdRC/CpCbmiu6+VaCa75dteWJ1QTexsjoTr8g=,iv:aXxdJWJGZHWGHwJv8wLbqDqkARE/j6UE7h6VLliOhY0=,tag:+8VY5iAZnxbqVCjjvNVRCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
