---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Berlin
  METALLB_LB_RANGE: 10.0.0.51-10.0.0.69,2a00:6020:4108:dc00:8000::/65
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.51,2a00:6020:4108:dc00:8000::1
  METALLB_INGRESS_ADDR: 10.0.0.52,2a00:6020:4108:dc00:8000::2
