---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.0.50-10.0.0.69
  METALLB_TRAEFIK_ADDR: 10.0.0.50
  MOSQUITTO_ADDR: 10.0.0.51
  HOME_ASSISTANT_ADDR: 10.0.0.52
  SYSLOG_ADDR: 10.0.0.53
