---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
#          cloudflare:
#            email: "${SECRET_CLOUDFLARE_EMAIL}"
#            apiKeySecretRef:
#              name: cloudflare-api-key
#              key: api-key
          route53:
            region: "${BOOTSTRAP_AWS_REGION}"
            accessKeyID: "${BOOTSTRAP_AWS_ACCESS_KEY_ID}"
            secretAccessKeySecretRef:
              name: aws-route53-secret-access-key
              key: secret-access-key
#            hostedZoneID: "${BOOTSTRAP_AWS_HOSTED_ZONE_ID}"
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
